version: '2'
services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - "${HOST_HTTP_PORT}:80"
    volumes:
      - ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-app:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./wp-database:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: ${ROOTPASSWORD}
  sidecar-backup-mysql:
    image: nutellinoit/sidecar-backup-mysql:1.0
    volumes:
        - ./dumpdb:/go/src/app/dumpdb
    restart: always
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${ROOTPASSWORD}
      - MYSQL_SQL_FILENAME=wordpress_backup
      - SCHEDULE=0 * * * * *

